blog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', blog_page, name='blog'),
    path('<int:id>/', blog_single_page, name='bsp'),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('courses/', include('course.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('', include('account.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', course_page, name='course'),
    path('csp/<str:slug>', course_single_page, name='csp'),
    path('topic/<str:id>', topic, name='topic'),

]

shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', shop_page, name='books'),
    path('product/<id>', product_page, name='book'),
    path('checkout/<slug:slug>', ChackOut_Function, name='checkout'),
    path('orderDone/', shop_completed, name='orderDone'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from django.contrib.auth import get_user_model
User = get_user_model()


class Category(models.Model):
    cat_name = models.CharField(max_length=50, unique=True)

    def get_url(self):
        return reverse('Category', args=[self.pk])
                                       
    def __str__(self):
        return self.cat_name

class News(models.Model):
    title = models.CharField(max_length=150, unique=True)
    description = models.TextField(max_length=700)
    images = models.ImageField(upload_to='news_images/')
    post_date = models.DateTimeField()
    post_author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def get_url(self):
        return reverse('bsp', args=[self.id])
    
    def __str__(self):
        return self.title

course/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class Categories(models.Model):
    icon = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Author(models.Model):
    author_profile = models.ImageField(upload_to="Media/author")
    name = models.CharField(max_length=100, null=True)
    about_author = models.TextField()

    def __str__(self):
        return self.name


class Course(models.Model):
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),
    )

    featured_image = models.ImageField(upload_to="Media/featured_img",null=True)
    featured_video = models.CharField(max_length=300,null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    author = models.ForeignKey(Author,on_delete=models.CASCADE,null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    description = models.TextField()
    price = models.IntegerField(null=True,default=0)
    discount = models.IntegerField(null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)




    def __str__(self):
        return self.title
    
class lessons(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name 

class Video(models.Model):
    seriul_number = models.IntegerField(null=True)
    thambnail = models.FileField(upload_to='thambnail', null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lesson = models.ForeignKey(lessons, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    video = models.FileField(upload_to='thambnail', null=True)
    time_duration = models.IntegerField(null=True)
    preview = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
class UserCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    paid = models.BooleanField(default=0)
    enrolled_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + " - " + self.course.title

class what_you_learn(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    point = models.CharField(max_length=100)
    def __str__(self):
        return self.point
    
class requirment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    point = models.CharField(max_length=100)
    def __str__(self):
        return self.point

shop/models.py
from django.db import models

# Create your models here.

class Bookcategory(models.Model):
    name=models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name
    

class BookModel(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField(max_length=500)
    cover = models.FileField(upload_to='book_cover')
    pdf = models.FileField(upload_to='book_pdf')
    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import *
from django.db.models import Q 
from django.core.paginator import Paginator


def blog_page(request):
    news = News.objects.all()
    category = Category.objects.all()
    lat_blog = News.objects.order_by('-post_date')[:3]


    #search function
    search = request.GET.get('q')                              
    if search:
        news = news.filter(
            Q(title__icontains=search)
            
        )

    #pageanation Logic
    paginator = Paginator(news, 1)
    page_number = request.GET.get('page')
    paginat_course = paginator.get_page(page_number)

    Context = {
        'news':paginat_course,
        'category':category,
        'lat_blog':lat_blog
    }
    return render(request, 'blog.html', Context)


def blog_single_page(request, id):
    news_singel = get_object_or_404(News, pk=id)                        #Single post filtaring
    lat_blog = News.objects.order_by('-post_date')[:3]                  #recent post filtaring
    Context = {
        'news_singel':news_singel,
        'lat_blog':lat_blog
    }
    return render(request, 'blog-single.html', Context)

course/views.py
from django.forms import SlugField
from django.shortcuts import render, get_object_or_404, redirect
from . models import *
from django.db.models import Q 
from django.db.models import Sum
from django.core.paginator import Paginator

# Create your views here.
def course_page(request):
    course_cat = Categories.objects.all().order_by('id')[0:5]                       #Course Category Filtering
    course = Course.objects.filter(status = 'PUBLISH').order_by('-id')              #Course Filtering by id

    for x in course:                                                                #course final price calculate
        x.final_price =x.price - x.price * x.discount / 100
    course_count = course.count()

    #search function
    search = request.GET.get('q')
    if search:
        course = course.filter(
            Q(title__icontains=search)
            
        )
    # pageanation Logic
    paginator = Paginator(course, 4)
    page_number = request.GET.get('page')
    paginat_course = paginator.get_page(page_number)

    #time_duration = Video.objects.filter(course__slug = slug).aaggregate(sum = Sum('time_duration'))


    Context = {
        'course':paginat_course,
        'course_cat':course_cat,
        'course_count':course_count,
        'search':search,
    }


    return render(request, 'product/course.html', Context)
def course_single_page(request, slug):

    course = get_object_or_404(Course, slug=slug)
    course_cat = Categories.objects.all()
    course_id = Course.objects.get(slug=slug)
    
    # enrolled course function
    enrolled_course = None

    if request.user.is_authenticated:
        try:
            enrolled_course = UserCourse.objects.get(user=request.user, course=course_id)

        except UserCourse.DoesNotExist:
            enrolled_course = None

    course.final_price = course.price - course.price * course.discount / 100

    context = {
        'course': course,
        'course_cat': course_cat,
        'enrolled_course': enrolled_course,
    }
    
    return render(request, 'product/course-single.html', context)


                                                                                # Catagory Function
def topic(request, id):
    category_cat = get_object_or_404(Categories, id=id)                         #Category single page function
    course = Course.objects.filter(category=category_cat.id)                    #Course filter by category
    course_cat = Categories.objects.all()
    course_count = course.count()
    context = {
        'course': course,
        'course_cat': course_cat,
        'course_count':course_count
    }
    return render(request, 'product/course_cat.html', context)

shop/views.py
from django.shortcuts import redirect, render, get_object_or_404
from course.models import * 
from .models import*


# Create your views here.
def shop_page(request):
    book = BookModel.objects.all()
    book_count = book.count()
    Context = {
        'book':book,
        'book_count':book_count,
    }
    return render(request, 'product/book.html', Context)
def product_page(request, id):
    book = get_object_or_404(BookModel, id=id)
    Context = {
        'book':book,
    }
    return render(request, 'product/single-book.html', Context)

def ChackOut_Function(request, slug):
    course = Course.objects.get(slug=slug)
    if course.price == 0:
        user_course = UserCourse(
            user=request.user,
            course=course,
        )
        user_course.save()
        return redirect('mainProfile', id=request.user.id)  # Pass the user ID here
    tax = (course.price / 100)*2
    total = course.price + tax
    context = {
        'course':course,
        'tax':tax,
        'total':total,
    }
    return render(request, 'checkout.html', context)

def shop_completed(request):
    return render(request, 'shop-order-completed.html')

templates/blog-single.html
{% extends 'core/base.html' %}
{% load static %}
{% block body %}
{% include 'core/home_menu.html' %}
<br><br><br><br><br><br><br><br><br>
    <!-- BLOG-SINGLE
    ================================================== -->
    <div class="container py-8 pt-lg-11">
        <div class="row">
            <div class="col-xl-8 mx-auto">
                <h1 class="text-capitalize">{{ news_singel.title }}</h1>

                <p class="me-xl-12">Master Figma app to get a job in UI Design, User Interface, User Experience design, Web Design & UX design.</p><br><br>
                <img src="{{ news_singel.images.url }}" alt="..." class="img-fluid rounded mb-8">

            </div>
        </div>
    </div>


    <div class="container">
        <div class="row mb-8 mb-md-12">
            <div class="col-xl-8 mx-auto">
                <h3 class="">Course Description</h3>
                <p class="mb-6 line-height-md">{{ news_singel.description }}</p>

                <blockquote>
                    <p>Aliquam hendrerit sollicitudin purus, quis rutrum mi accumsan nec. Quisque bibendum orci ac nibh facilisis, at malesuada orci congue.
                        <cite>Luis Pickford</cite>
                    </p>
                </blockquote>


                

                <h3 class="mb-5">Requirements</h3>
                <ul class="list-style-v2 list-unstyled mb-10">
                    <li>We do not require any previous experience or pre-defined skills to take this course. A great orientation would be enough to master UI/UX design.</li>
                    <li>A computer with a good internet connection.</li>
                    <li>Adobe Photoshop (OPTIONAL)</li>
                </ul>

            </div>
        </div>

        <div class="row align-items-end mb-4 mb-md-7">
            <div class="col-md mb-4 mb-md-0">
                <h1 class="mb-1">Latest News</h1>
                <p class="font-size-lg mb-0 text-capitalize">Discover your perfect program in our courses.</p>
            </div>
            <div class="col-md-auto">
                <a href="{% url 'blog' %}" class="d-flex align-items-center fw-medium">
                    Browse All
                    <div class="ms-2 d-flex">
                        <!-- Icon -->
                        <i class="fa-solid fa-arrow-right"></i>
                    </div>
                </a>
            </div>
        </div>

        <div class="row row-cols-md-2 row-cols-lg-3 mb-8 mb-md-11">
            {% for resent in lat_blog %}
            <div class="col-md mb-5 mb-lg-0">
                <!-- Card -->
                <div class="card border shadow p-2 lift sk-fade">
                    <!-- Image -->
                    <div class="card-zoom position-relative">
                        <a href="course-single-v1.html" class="card-img d-block sk-thumbnail img-ratio-3"><img class="rounded shadow-light-lg img-fluid" src="{{ resent.images.url }}" alt="..."></a>

                        <a href="course-single-v1.html" class="badge sk-fade-bottom badge-lg badge-purple badge-pill badge-float bottom-0 left-0 mb-4 ms-4 px-5 me-4">
                            <span class="text-white fw-normal font-size-sm">{{ resent.category }}</span>
                        </a>
                    </div>

                    <!-- Footer -->
                    <div class="card-footer px-2 pb-0 pt-4">
                        <ul class="nav mx-n3 mb-3">
                            <li class="nav-item px-3">
                                <a href="course-single-v1.html" class="d-flex align-items-center text-gray-800">
                                    <div class="me-3 d-flex">
                                        <!-- Icon -->
                                        <i class="fa-solid fa-user"></i>
                                    </div>
                                    <div class="font-size-sm">{{ resent.post_author }}</div>
                                </a>
                            </li>
                            <li class="nav-item px-3">
                                <a href="course-single-v1.html" class="d-flex align-items-center text-gray-800">
                                    <div class="me-2 d-flex">
                                        <!-- Icon -->
                                        <i class="fa-solid fa-calendar-days"></i>
                                    </div>
                                    <div class="font-size-sm">{{ resent.post_author }}</div>
                                </a>
                            </li>
                        </ul>

                        <!-- Heading -->
                        <a href="course-single-v1.html" class="d-block"><h5 class="line-clamp-2 h-48 h-lg-52">{{ resent.post_author }}</h5></a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% include 'core/footer.html' %}

{% endblock %}

templates/blog.html
{% extends 'core/base.html' %}
{% load static %}
{% block body %}
{% include 'core/home_menu.html' %}


    <!-- PAGE TITLE
    ================================================== -->
    <header class="py-8 py-md-11" style="background-image: none;">
        <div class="container text-center py-xl-2">
            <h1 class="display-4 fw-semi-bold mb-0">Blog List v1</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-scroll justify-content-center">
                    <li class="breadcrumb-item">
                        <a class="text-gray-800" href="#">
                            Home
                        </a>
                    </li>
                    <li class="breadcrumb-item text-gray-800 active" aria-current="page">
                        Blog List v1
                    </li>
                </ol>
            </nav>
        </div>
        <!-- Img -->
        <img class="d-none img-fluid" src="...html" alt="...">
    </header>


    <!-- BLOG LIST V1
    ================================================== -->
    <div class="container mb-11">
        <div class="row">
            <div class="col-md-7 col-lg-8 col-xl-9 mb-5 mb-md-0">
                {% for news in news %}
                <!-- Blog Post -->
                <div class="row mb-6 align-items-center">
                    <div class="col-lg-6 col-xl-5 mb-6 mb-lg-0">
                        <a href="{{ news.get_url }}" class="d-block sk-thumbnail img-ratio-4 rounded lift">
                            <img src="{{ news.images.url }}" alt="Image Loading...." class="rounded img-fluid">
                        </a>
                    </div>

                    <div class="col-lg-6 col-xl-7">
                        <a href="blog-single.html" class="d-inline-block">
                            <h5 class="text-blue">{{ news.category }}</h5>
                        </a>

                        <a href="{{ news.get_url }}" class="d-block me-xl-12">
                            <h3 class="">{{ news.title }}</h3>
                        </a>

                        <p class="line-clamp-3 mb-6 mb-xl-8 me-xl-6">{{ news.description }}</p>

                        <div class="d-md-flex align-items-center">
                            <div class="border rounded-circle d-inline-block mb-4 mb-md-0 me-4">
                                <div class="p-1">
                                    <img src="{% static 'assets/img/avatars/avatar-1.jpg' %}" alt="..." class="rounded-circle" width="52" height="52">
                                </div>
                            </div>

                            <div class="mb-4 mb-md-0">
                                <a href="blog-single.html" class="d-block"><h6 class="mb-0">{{ news.post_author }}</h6></a>
                                <span class="font-size-sm">{{ news.post_date }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

                    <!-- PAGINATION
    ================================================== -->
    <nav class="mt-8" aria-label="Page navigationa">
        <ul class="pagination justify-content-center">
        {% if news.has_previous %}
            <li class="page-item">
            <!--
                <a class="page-link" href="?page=1" tabindex="-1" aria-label="Previous">
                    <span aria-hidden="true"><i class="fas fa-arrow-left"></i></span>
                </a>
            -->
                <a class="page-link" href="?page={{ news.previous_page_number }}" tabindex="-1" aria-label="Previous">
                    <span aria-hidden="true"><i class="fas fa-arrow-left"></i></span>
                </a>

                
            </li>
        {% endif %}

        {% for page_num in news.paginator.page_range %}
            <li class="page-item"><a class="page-link {% if page_num == news.number %} current{% endif %}" href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endfor %}

        {% if news.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ news.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true"><i class="fas fa-arrow-right"></i></span>
                </a>
                <!--
                <a class="page-link" href="?page={{ blogging.paginator.num_pages }}" aria-label="Next">
                    <span aria-hidden="true"><i class="fas fa-arrow-right"></i></span>
                </a>
                -->
                
            </li>
        {% endif %}
        </ul>
    </nav>

            </div>

            <div class="col-md-5 col-lg-4 col-xl-3">
                <!-- BLOG SIDEBAR
                ================================================== -->
                <div class="">
                    <form class="" action="" method = 'GET'>
                        <div class="border rounded mb-6">
                            <div class="input-group">
                                <input class="form-control form-control-sm placeholder-dark border-end-0 shadow-none" type="text" name='q' placeholder="Type a keyword" value = "{{request.GET.q}}" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-sm my-2 my-sm-0 text-secondary icon-uxs" type="submit">
                                        <!-- Icon -->
                                        <i class="fa-solid fa-magnifying-glass"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="border rounded mb-6 p-5 py-md-6 ps-md-6 pe-md-4">
                        <h4 class="mb-5">Category</h4>
                        <div class="nav flex-column nav-vertical">
                            {% for cat in category %}
                            <a href="#" class="nav-link py-2">{{ cat.cat_name }} ({{ cat.news_set.all.count }})</a>
                            {% endfor %}
                        
                        </div>
                    </div>

                    <div class="border rounded mb-6 p-5 py-md-6 ps-md-6 pe-md-4">
                        <h4 class="mb-5">Recent Posts</h4>
                        <ul class="list-unstyled mb-0">
                            {% for resent in lat_blog %}
                            <li class="media mb-6 d-flex">
                                <a href="blog-single.html" class="mw-70p d-block me-5">
                                    <img src="{{ resent.images.url }}" alt="..." class="avatar-img rounded-lg h-70p o-f-c">
                                </a>
                                <div class="media-body flex-shrink-1">
                                    <a href="blog-single.html" class="d-block">
                                        <h6 class="line-clamp-2 mb-1 fw-normal">{{ resent.title }}</h6>
                                    </a>
                                    <span>{{ resent.post_date }}</span>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% include 'core/footer.html' %}

{% endblock %}

templates/checkout.html
{% extends 'core/base.html' %}
{% load static %}
{% block body %}
{% include 'core/home_menu.html' %}
    <!-- PAGE TITLE
    ================================================== -->
    <header class="py-8 py-md-10" style="background-image: none;">
        <div class="container text-center py-xl-2">
            <h1 class="display-4 fw-semi-bold mb-0">Shop Checkout</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-scroll justify-content-center">
                    <li class="breadcrumb-item">
                        <a class="text-gray-800" href="#">
                            Home
                        </a>
                    </li>
                    <li class="breadcrumb-item text-gray-800 active" aria-current="page">
                        Shop Checkout
                    </li>
                </ol>
            </nav>
        </div>
        <!-- Img -->
        <img class="d-none img-fluid" src="...html" alt="...">
    </header>


    <!-- SHOP CHECKOUT
    ================================================== -->
    <div class="container pb-6 pb-xl-10">
        <form name="checkout" method="post" class="checkout woocommerce-checkout" action="https://transvelo.github.io/skola-html/5.1/..." novalidate="">
            <div class="col2-set" id="customer_details">
                <div class="col-1">
                    <div class="woocommerce-billing-fields">
                        <h3>Billing details</h3>
                        <div class="woocommerce-billing-fields__field-wrapper">
                            <p class="form-row form-row-first validate-required woocommerce-invalid woocommerce-invalid-required-field" id="billing_first_name_field" data-priority="10">
                                <label for="billing_first_name" class="">First name <abbr class="required" title="required">*</abbr></label>
                                <input type="text" class="input-text " name="billing_first_name" id="billing_first_name" placeholder="" value="" autocomplete="given-name" autofocus="autofocus">
                            </p>
                            <p class="form-row form-row-last validate-required" id="billing_last_name_field" data-priority="20">
                                <label for="billing_last_name" class="">Last name <abbr class="required" title="required">*</abbr></label>
                                <input type="text" class="input-text " name="billing_last_name" id="billing_last_name" placeholder="" value="" autocomplete="family-name">
                            </p>

                            <p class="form-row form-row-first validate-required woocommerce-invalid woocommerce-invalid-required-field" id="billing_first_name_field" data-priority="10">
                                <label for="billing_first_name" class="">Email Address <abbr class="required" title="required">*</abbr></label>
                                <input type="text" class="input-text " name="billing_first_name" id="billing_first_name" placeholder="" value="" autocomplete="given-name" autofocus="autofocus">
                            </p>
                            <p class="form-row form-row-last validate-required" id="billing_last_name_field" data-priority="20">
                                <label for="billing_last_name" class="">Phone Number <abbr class="required" title="required">*</abbr></label>
                                <input type="text" class="input-text " name="billing_last_name" id="billing_last_name" placeholder="" value="" autocomplete="family-name">
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-2">
                    <div class="woocommerce-shipping-fields"></div>
                    <div class="woocommerce-additional-fields">
                        <div class="woocommerce-additional-fields__field-wrapper">
                            <p class="form-row notes" id="order_comments_field" data-priority=""><label for="order_comments" class="">Extra notes if you have</label><textarea name="order_comments" class="input-text " id="order_comments" placeholder="Notes about your order, e.g. special notes for delivery." rows="7" cols="5"></textarea></p>
                        </div>
                    </div>
                </div>
            </div>

            <div id="order_review" class="woocommerce-checkout-review-order">
                <div class="woocommerce-checkout-review-order-inner">
                    <h3 id="order_review_heading">Your order</h3>
                    <table class="shop_table woocommerce-checkout-review-order-table">
                        <thead>
                            <tr>
                                
                                <h5 class="">{{ course.title}}</h5>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="cart-subtotal">
                                <th>Price</th>
                                <td><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">৳ </span> {{ course.price }}</span></td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr class="cart-subtotal">
                                <th>Vat / Tax</th>
                                <td><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">৳ </span> {{ tax }}</span></td>
                            </tr>

                            <tr class="order-total">
                                <th>Total</th>
                                <td><strong><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">৳ </span>{{total}}</span></strong> </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>

                <div id="payment" class="woocommerce-checkout-payment">
                    <ul class="wc_payment_methods payment_methods methods">
                        <li class="wc_payment_method payment_method_bacs">
                            <label for="payment_method_bacs">Bkash, Nogod, Roket ( payment screensot )</label>
                            <div class="payment_box payment_method_bacs" style="display: block;">
                                <input type="file" class="input-text " name="billing_first_name" id="billing_first_name" placeholder="" value="" autocomplete="given-name" autofocus="autofocus">
                            </div>
                        </li>
                    </ul>
                    <div class="form-row place-order">
                        <a href="shop-order-completed.html" class="btn btn-primary btn-block">
                            PLACE ORDER
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <!-- CALL ACTION
    ================================================== -->
    <section class="py-6 py-md-11 border-top border-bottom" data-jarallax data-speed=".8" style="background-image: url(assets/img/illustrations/illustration-1.jpg)">
        <div class="container text-center py-xl-4" data-aos="fade-up">
            <div class="row">
                <div class="col-xl-7 mx-auto">
                    <h1 class="text-capitalize">Subscribe our newsletter</h1>
                    <p class="text-capitalize font-size-lg mb-md-6 mb-4">Your download should start automatically, if not Click here. Should I give up, huh?.</p>
                    <div class="mx-md-8">
                        <form>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Enter your email" aria-label="Enter your email" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary btn-sm-wide" type="button" id="button-addon2">Subscribe</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}